// Демо-контент. Використовується, коли Supabase ще не підключено,
// щоб сайт одразу виглядав живим і наповненим.
// Коли база запрацює — реальні дані замінять ці автоматично.

export const seedWorks = [
  {
    id: 'seed-1',
    title_uk: 'Ніжна арка для першого рочка',
    title_ru: 'Нежная арка для первого годика',
    description_uk: 'Пастельні відтінки, бабоки та іменна табличка.',
    description_ru: 'Пастельные оттенки, бабочки и именная табличка.',
    image_url: '/works/gallery-4.jpg',
    category: 'firstYear',
    featured: true,
    sort_order: 1,
  },
  {
    id: 'seed-2',
    title_uk: 'Рожева фотозона Happy Birthday',
    title_ru: 'Розовая фотозона Happy Birthday',
    description_uk: 'Фатиновий фон, неон і дзеркальні кулі.',
    description_ru: 'Фатиновый фон, неон и зеркальные шары.',
    image_url: '/works/gallery-2.jpg',
    category: 'birthday',
    featured: true,
    sort_order: 2,
  },
  {
    id: 'seed-3',
    title_uk: 'Весільна президія з перлами',
    title_ru: 'Свадебный президиум с жемчугом',
    description_uk: 'Біла драпіровка, перли та іменні написи.',
    description_ru: 'Белая драпировка, жемчуг и именные надписи.',
    image_url: '/works/gallery-3.jpg',
    category: 'wedding',
    featured: true,
    sort_order: 3,
  },
  {
    id: 'seed-4',
    title_uk: 'Фіолетова казка з бабоками',
    title_ru: 'Фиолетовая сказка с бабочками',
    description_uk: 'Гірлянда з кульок, фея та золоті акценти.',
    description_ru: 'Гирлянда из шаров, фея и золотые акценты.',
    image_url: '/works/gallery-1.jpg',
    category: 'birthday',
    featured: true,
    sort_order: 4,
  },
  {
    id: 'seed-5',
    title_uk: 'Світле оформлення baby shower',
    title_ru: 'Светлое оформление baby shower',
    description_uk: 'Ніжні кульки й делікатний декор.',
    description_ru: 'Нежные шары и деликатный декор.',
    image_url: '/works/gallery-5.jpg',
    category: 'baby',
    featured: true,
    sort_order: 5,
  },
];

export const seedPrices = [
  {
    id: 'p1',
    name_uk: 'Гелієві кульки',
    name_ru: 'Гелиевые шары',
    description_uk: 'Букети та композиції, що тримаються весь вечір',
    description_ru: 'Букеты и композиции, которые держатся весь вечер',
    price_from: 2500,
    unit_uk: 'за композицію',
    unit_ru: 'за композицию',
    sort_order: 1,
  },
  {
    id: 'p2',
    name_uk: 'Декор дому / виписка',
    name_ru: 'Декор дома / выписка',
    description_uk: 'Оформлення кімнати до особливої події',
    description_ru: 'Оформление комнаты к особому событию',
    price_from: 3500,
    unit_uk: 'за оформлення',
    unit_ru: 'за оформление',
    sort_order: 2,
  },
  {
    id: 'p3',
    name_uk: 'Фотозона під ключ',
    name_ru: 'Фотозона под ключ',
    description_uk: 'Повне оформлення простору для фотосесії',
    description_ru: 'Полное оформление пространства для фотосессии',
    price_from: 6000,
    unit_uk: 'за фотозону',
    unit_ru: 'за фотозону',
    sort_order: 3,
  },
  {
    id: 'p4',
    name_uk: 'Оформлення залу',
    name_ru: 'Оформление зала',
    description_uk: 'Весілля, ювілеї, корпоративи',
    description_ru: 'Свадьбы, юбилеи, корпоративы',
    price_from: 9000,
    unit_uk: 'за захід',
    unit_ru: 'за мероприятие',
    sort_order: 4,
  },
];

// Контент, який можна редагувати з адмінки (контакти тощо).
export const seedContent = {
  phone: '+38 (099) 354 60 48',
  phone_raw: '380993546048',
  instagram: 'https://www.instagram.com/balloons_decor_zp/',
  telegram: 'https://t.me/balloons_decor_zp',
  email: '',
};
